package com.indistudia;

import com.indistudia.config.DbConfig;
import com.indistudia.repository.MigrationRepository;
import com.indistudia.repository.TodoRepository;
import com.indistudia.repository.UsersRepository;

import java.util.UUID;

public class Main {
    public static void main(String[] args) {
        var dbConfig = new DbConfig(
                "jdbc:postgresql://localhost:8432/todolist",
                "todolist",
                "todolist"
        );
/*
        var connection = DriverManager.getConnection(
                dbConfig.jdbcUrl(),
                dbConfig.user(),
                dbConfig.password()
        );

//        PreparedStatement preparedStatement = connection.prepareStatement("""
//                CREATE TABLE users(
//                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//                    name varchar(50) UNIQUE NOT NULL,
//                    age int CHECK ( age > 0 ) NOT NULL
//                );
//                """);

//        connection.prepareStatement("""
//                INSERT INTO users(name, age) VALUES ('MAksim', 21);
//                """).execute();

        final String SQL_TO_FIND_USER = "SELECT * FROM users WHERE id = ?";

        var prepStatement = connection.prepareStatement(SQL_TO_FIND_USER);
        prepStatement.setInt(1, 1);
        var rs = prepStatement.executeQuery();
        *//*
        execute - void, выполняет операцию и ничего не возвращает. подходит для ins/update/delete.
        executeQuery - возвращает ResultSet -- результат выполнения операции.
         *//*

        while (rs.next()) {
            var id = rs.getInt("id");
            var name = rs.getString("name");
            var age = rs.getInt("age");

            System.out.println("id=" + id + ", name=" + name + ", age=" + age);
        }
        System.out.println("-----------------------");

        final String SQL_TO_FIND_ALL_USERS = "SELECT * FROM users";
        var rs2 = connection.prepareStatement(SQL_TO_FIND_ALL_USERS).executeQuery();

        while (rs2.next()) {
            var id = rs2.getInt("id");
            var name = rs2.getString("name");
            var age = rs2.getInt("age");

            System.out.println("id=" + id + ", name=" + name + ", age=" + age);
        }

        *//*
        nextval():
        1) мы берем наш шаг start with, смотрим на массив listValues и проверяем, пустой он или нет. Если да,
        мы заранее просчитываем batch size следующих значений.
        То есть: если SW = 1, batchSize = 20, то в нашем массиве  listValues будут лежать значения от 1 до 1+21 включительно.
        ЗОЧЕМ?
        Чтобы при каждом вызове nextval не делать вычисления, а взять следующий элемент массива.

        1) генерируете айди пользователя путем запроса id = select nextval() from users_id_seq
        2) делаете insert into users(id, name, age) values (id, ?name, ?age);
        падаем на шаге 2 так как не выполняется уникальности имени. НО! вы уже выбрали следующий элемент из сиквенса
         *//*

         *//*
        у джбс тоже бач сайз
        когад вы делаете селект, джбс делакт селект бач сайзом.
        а потом начинаем из вот этого вашего бач сайза отдавать вам строки.
        То если вы сделаете select * from table_with_10_mlns_rows; и batchSize = 500, то в память вы выгрузите ровно 500 элементов.

        на каждый запрос JDBC делает следующие действия:
        1) check connection
        2) try to execute query -> can execute (no available connections)
        3) execute query()
        4) get result from db.
         *//*

        try (var connect = DbManager.getConnection(dbConfig)) {
            var rs3 = connect.prepareStatement("SELECT * FROM users WHERE id > 1").executeQuery();

            while (rs3.next()) {
                var id = rs3.getInt("id");
                var name = rs3.getString("name");
                var age = rs3.getInt("age");
                System.out.println("id=" + id + ", name=" + name + ", age=" + age);
            }
        } catch (RuntimeException exception) {
            System.out.println(exception.getMessage());
        }*/

        var migrationRepo = new MigrationRepository(dbConfig);
        var userRepo = new UsersRepository(dbConfig);
        var todoRepo = new TodoRepository(dbConfig);

        migrationRepo.initTables();
        todoRepo.addTodo("Выпить пиво", 1L);
        todoRepo.findAllUsersTodos(1L).forEach(System.out::println);
        System.out.println("--------");
        todoRepo.addTodo("Провести собес", 1L);
        todoRepo.findAllUsersTodos(1L).forEach(System.out::println);
        System.out.println("--------");

        todoRepo.completeTodo(UUID.fromString("52fb5092-ed3e-4939-991d-51d8626fcb04"), 1L);
        todoRepo.findAllUsersTodos(1L).forEach(System.out::println);


    }
}