package com.indistudia.repository;

import com.indistudia.config.DbConfig;
import com.indistudia.config.DbManager;

import java.sql.SQLException;

public class MigrationRepository {
    private final String INIT_USERS_TABLE_QUERY = """
            CREATE TABLE IF NOT EXISTS users(
                                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name varchar(50) UNIQUE NOT NULL,
                                age int CHECK ( age > 0 ) NOT NULL
                            );
            """;
    private final String INIT_TODO_TABLE_QUERY = """
            CREATE TABLE IF NOT EXISTS todos(
            id uuid PRIMARY KEY,
            title varchar(155) NOT NULL,
            is_completed bool DEFAULT FALSE,
            user_id bigint REFERENCES users(id)
            );
            """;

    private final DbConfig dbConfig;

    public MigrationRepository(DbConfig dbConfig) {
        this.dbConfig = dbConfig;
    }

    public void initTables() {
        try (var connection = DbManager.getConnection(dbConfig)) {
            connection.prepareStatement(INIT_USERS_TABLE_QUERY).execute();
            connection.prepareStatement(INIT_TODO_TABLE_QUERY).execute();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
}
